import { Inter } from "next/font/google";
import "./globals.css";
import headerStyles from "./header.module.css"
import footerStyles from "./footer.module.css"

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className={headerStyles.header}>This is the Header</header>
        <h2 className="bg-red-500 text-center">I'm red and centered</h2>
        {children}
        <footer className={footerStyles.footer}>This is the Footer</footer>
        </body>
    </html>
  );
}
