import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>This is header herrooo</header>
        <nav>
          <Link href="/">HOME</Link> | <Link href="/about">ABOUT</Link> | <Link href="/posts">POSTS</Link> 
        </nav>
        <div className="container">
        {children}
        </div>
        <footer>This is footer bye byeee</footer>
        </body>
    </html>
  );
}
