import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <header>Header</header>
      <nav>
        <Link href="/">Home</Link>
        <Link href="/about">About</Link>
        <Link href="/posts/1">Post 1</Link>
        <Link href="/posts/2">Post 2</Link>
        <Link href="/posts/3">Post 3</Link>
      </nav>
        {children}
      <footer>Footer</footer>
      </body>
    </html>
  );
}
